name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run tests
        run: mvn test
        continue-on-error: true

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Upload Artifact - Allure Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/allure-report/

      - name: Upload Artifact - Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: target/logs/

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/